version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:333427308013:task-definition/node-api:8"
        LoadBalancerInfo:
          ContainerName: "node-api"
          ContainerPort: 3000
        PlatformVersion: "LATEST"