version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - aws --version
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Testing started on `date`
      - npm run test
      - echo Build started on `date`

      - echo IMAGE_TAG
      - echo $IMAGE_TAG
      
      - echo Building the Docker image...
      - docker build -t thaddavis/node-api:latest .
      - docker tag thaddavis/node-api:latest thaddavis/node-api:$IMAGE_TAG
      - docker push thaddavis/node-api:$IMAGE_TAG
      
      - sed -i "s/IMAGE_TAG/$IMAGE_TAG/" taskdef.json
      - TASK_VERSION=$(aws ecs register-task-definition --cli-input-json file://taskdef.json | jq --raw-output '.taskDefinition.revision')
      
      - echo Debugging TASK_VERSION
      - echo $TASK_VERSION

      - sed -i "s/TASK_VERSION/$TASK_VERSION/" appspec.yaml
      - echo Debugging appspec.yaml
      - cat appspec.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files: appspec.yaml